namespace: demo-app
replicas: 1

image:
  repository: demo-app.repo.com
  tag: latest

containerPort: 8080

hpa:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

service:
  nodePort: 30088

resources:
  requests:
    cpu: 100m
  limits:
    cpu: 600m